---
layout: cv
title: Conner Gardiner's CV
---
# Conner Gardiner
Pre-Professional | Biomedical & Computer Science | BYU-Idaho

<div id="webaddress">
<a href="gar21051@byui.edu">gar21051@byui.edu</a>
| <a href="https://www.linkedin.com/in/conner-gardiner/">Connect on LinkedIn Page</a>
</div>


## Currently

Your life can either be a tragedy of the what could've been, or a Hero's Journey of who you became along the way. 

Either way, the choice is either made by you, or for you. 

So, what will the next series of incremental, daily decisions decide for you?

### Specialized in

Dynamic critical thinking, interpersonal communication, team-building, and making the 'journey' worthwhile one day at a time

### Research interests

AWS, Scaling Cloud Databases, Network Engineering, Infastructure & Development, User Experience.


## Education

`2021-Now`
__Brigham Young University Idaho__

`2022`
__Weber State University__


`2018`
__Layton High School__



## Occupation

`OCT 2023- JUL 2024`
Collaborated on Figma with clients, showcasing design elements, bringing the vision to life

Enhanced SEO, utilizing local reviews, keywords, UX design, and image optimization

Executed in framework Astro using JavaScript, React, and Tailwind in development stack

Improved organic traffic by 78.8% in Q1 by reconfiguring SEO, media channels, and overhauling site

__Jr Web Developer - Freelance__

`2024`
Achieved 99.2% data input accuracy, ensuring client account reliability, fostering organic growth

Streamlined communication channels, optimizing collaboration and synergy across departments

Utilized advanced Excel functions to streamline analysis, contributing to overall clientele retention

Performed regular audits of safeguarded accounts, enhancing data integrity and decision making

__Data Processing Analyst - Rocky Mountain Reserve__


`2023`
Led comprehensive site surveys across multiple government facilities, effectively assessing over 300 MDF and IDF closets to capture vital data on network infrastructure and environmental conditions

Diligently recorded details on networking hardware, including model numbers, serial numbers, location, and rack elevations, ensuring accurate and thorough documentation

Examined and documented patch panel configurations, providing precise cable counts and identifying cable types to facilitate infrastructure upgrades

Captured detailed photographs of rooms, equipment racks, and networking components, aiding in future infrastructure planning and assessments

Produced comprehensive reports post-survey, detailing findings and recommendations for future infrastructure improvements and optimizations

Underwent rigorous specialized training for environments with radioactive hazards, ensuring safety and compliance during all survey operations

__Network Survey Specialist - (Government Facilities)__



<!-- ### Footer

Last updated: May 2013 -->